### PR TITLE
Honor CSS transformations of the element the popover is attached to.

### PR DESCRIPTION
**Pull request by anlumo**

### CODE REVIEW

**Comment by jeremyVignelles** [comment]
I just submitted a PR for the needs of my feature : popover inside a container.
I merged your change in #161 . Could you please check that my PR also solve your issue?

**Comment by jeremyVignelles** [comment]
@anlumo If you want to test my PR, I made an unofficial release for this. See : https://github.com/jeremyVignelles/webui-popover/tree/7d89959051117dca95e3fd2c4a813c1f607779bb
If you are using bower, you can just link to that revision and see if it works.

**Comment by anlumo** [comment]
Will do, thank you!

**Comment by anlumo** [comment]
Sorry for the very very late response. The issue has been fixed for me in the latest release.

**Pull request merged**
